### ISSUE TITLE
how to train step by step?

### ISSUE THREAD

**Issue by Issac304** [VILAN-Lab/PBREC-MT#2]

**Comment by william1111111111** [comment]
Firstly, as Issue 1 suggested, download the specified dataset and place it in the project.
 [https://github.com/VILAN-Lab/PBREC-MT/issues/1](url)

Secondly, determine your training type, whether it is detection, segmentation, or both detection and segmentation, and you can make the necessary modifications in the shell script (sh file) or the train.py file.

Thirdly, use 'nohup ./train.sh > ./log/refcoco.log 2>&1 &' to run train.sh

Fourth, After the model has finished training, for a given input sample, the model will output a probability tensor of shape (400,). This corresponds to the predictions for each region block in the object detectors SOLO and FCOS, where each block has one prediction value (either a bounding box or a mask).
SOLO: [https://github.com/WXinlong/SOLO](url)
FCOS: [https://github.com/tianzhi0549/FCOS](url) (In SOLO, due to varying scales, linear interpolation is used to meet the scale requirements of SOLO.)

Last, Based on the settings of the hyperparameters, we will obtain N boxes, which will then undergo post-processing using the IOU-NMS method we proposed.
Hope that will be help. @Issac304

**Comment by Issac304** [comment]
https://github.com/VILAN-Lab/PBREC-MT/issues/1](https://github.com/VILAN-Lab/PBREC-MT/issues/url) 
OK，but there has nothing
